# rosalind/tools/powerbi.py
from typing import Dict, List, Optional
import textwrap

def generate_dax_measure(
    measure_name: str,
    expression: str,
    description: str = "",
    format_string: str = "#,##0"
) -> str:
    """
    Generate a clean, commented, production-ready DAX measure
    """
    template = f"""
-- =============================================
-- Measure: {measure_name}
-- Description: {description or "No description provided"}
-- Generated by Rosalind AI Analyst
-- =============================================
{measure_name} = 
VAR __Result = 
    {textwrap.indent(expression.strip(), "    ")}
RETURN
    IF(
        ISINSCOPE('Date'),  -- Adjust table name if needed
        __Result,
        BLANK()
    )
    
// Format: {format_string}
"""
    return textwrap.dedent(template).strip() + "\n"


def generate_common_measures(df_summary: Dict) -> List[str]:
    """
    Auto-generate the most requested DAX measures based on data
    """
    measures = []
    
    # Total Revenue
    revenue_cols = [c for c in df_summary.get("numeric_columns", []) if "revenue" in c.lower() or "sales" in c.lower() or "amount" in c.lower()]
    if revenue_cols:
        col = revenue_cols[0]
        measures.append(generate_dax_measure(
            measure_name="Total Revenue",
            expression=f"SUM('{df_summary['table_name']}[{col}])",
            description="Sum of all revenue/sales",
            format_string="KES #,##0"
        ))
        
        measures.append(generate_dax_measure(
            measure_name="YoY Growth %",
            expression=f"""
                VAR CurrentPeriod = [Total Revenue]
                VAR PreviousPeriod = 
                    CALCULATE(
                        [Total Revenue],
                        DATEADD('Date'[Date], -1, YEAR)
                    )
                RETURN
                    DIVIDE(CurrentPeriod - PreviousPeriod, PreviousPeriod)
            """,
            description="Year-over-Year revenue growth",
            format_string="0.0%"
        ))
    
    # Customer Count
    customer_cols = [c for c in df_summary.get("columns", []) if "customer" in c.lower() or "client" in c.lower()]
    if customer_cols:
        measures.append(generate_dax_measure(
            measure_name="Active Customers",
            expression=f"DISTINCTCOUNT('{df_summary['table_name']}[{customer_cols[0]}])",
            description="Number of unique customers"
        ))
    
    # Average Transaction Value
    if revenue_cols and customer_cols:
        measures.append(generate_dax_measure(
            measure_name="Avg Transaction Value",
            expression=f"DIVIDE([Total Revenue], [Active Customers])",
            description="Average revenue per customer/transaction",
            format_string="KES #,##0"
        ))
    
    return measures


def create_dax_snippets(request: str, df_summary: Dict) -> str:
    """
    Main tool called by the agent – returns ready-to-paste DAX
    """
    request_lower = request.lower()
    result = ["-- ROSALIND GENERATED DAX MEASURES"]
    result.append(f"-- Dataset: {df_summary.get('table_name', 'Data')}")
    result.append(f"-- Rows: {df_summary.get('row_count', 'Unknown'):,}")
    result.append("")

    # Common auto-measures
    if any(word in request_lower for word in ["all", "common", "standard", "default"]):
        result.extend(generate_common_measures(df_summary))
    
    # Specific requests
    if "yoy" in request_lower or "year over year" in request_lower:
        result.append(generate_dax_measure(
            "YoY Growth %",
            """
                VAR Current = [Total Revenue]
                VAR Previous = CALCULATE([Total Revenue], DATEADD('Date'[Date], -1, YEAR))
                RETURN DIVIDE(Current - Previous, Previous)
            """,
            "Year-over-Year growth percentage"
        ))
    
    if "mtd" in request_lower:
        result.append(generate_dax_measure(
            "Revenue MTD",
            "CALCULATE([Total Revenue], DATESMTD('Date'[Date]))",
            "Month-to-Date Revenue"
        ))
    
    if "running total" in request_lower:
        result.append(generate_dax_measure(
            "Revenue Running Total",
            """
                CALCULATE(
                    [Total Revenue],
                    FILTER(
                        ALLSELECTED('Date'),
                        'Date'[Date] <= MAX('Date'[Date])
                    )
                )
            """,
            "Cumulative revenue over time"
        ))
    
    final_dax = "\n\n".join(result)
    print("DAX measures generated and ready for Power BI")
    return final_dax
